### ISSUE TITLE
who can use the plugin?

### ISSUE THREAD

**Issue by cjl628-cjl** [lispycpp/zlgcan#1]
how to use?
![image](https://github.com/lispycpp/zlgcan/assets/83996356/be2f7e95-eac0-44d5-8089-df8c25ce18a7)

No Interface name.
this blank should be "can0"!

**Comment by lispycpp** [comment]
you need download and install CAN driver first, then download api dll and place it on your app.exe directory.
driver and api dll link is [zlgcan](https://www.zlg.cn/can/down/down/id/22.html)

**Comment by lispycpp** [comment]
api dll is "zlgcan二次开发接口函数库/zlgcan_*" according your platform

**Comment by cjl628-cjl** [comment]
Thank you for your reply。At last，I used the plugin：
https://www.bilibili.com/video/BV1kk8FeuEvc/?spm_id_from=333.999.0.0&vd_source=ed38746b0c1b6c78626e7a4440bc64fa
